Update
Signed-off-by: Arthur Lapz <rlapz@gnuweeb.org>

diff --git a/.local/bin/chdns b/.local/bin/chdns
--- a/.local/bin/chdns
+++ b/.local/bin/chdns
@@ -1,8 +1,81 @@
 #!/bin/sh
 
 
-[ -z "$1" ] && exit
+#------------------------------------------------------#
+help_msg() {
+    cat << EOF
+chdns [OPT] [DNS]
+      -e    - Print /etc/resolv.conf contents
+      -s    - Set dns
+      -a    - Append dns
+      -h    - Show help
 
-echo "nameserver $1" > /etc/resolv.conf && echo "Done!" && exit
+Examples:
+      chdns -e
+      chdns -s 127.0.0.1
+      chdns -a 127.0.0.1
 
-echo "Failed!"
+EOF
+}
+
+
+err()
+{
+	printf "%s\n\n" "Invalid argument!" >&2
+	help_msg >&2
+
+	exit 1
+}
+
+
+set_dns()
+{
+	cat << EOF > /etc/resolv.conf
+# Generated by chnds
+nameserver $1
+
+EOF
+}
+
+
+append_dns()
+{
+	cat << EOF >> /etc/resolv.conf
+nameserver $1
+
+EOF
+}
+
+
+#------------------------------------------------------#
+case "$1" in
+"-e")
+	cat /etc/resolv.conf
+	;;
+
+"-s")
+	[ -z "$2" ] && err
+
+	if set_dns "$2"
+	then
+		echo "Done!"
+	fi
+	;;
+
+"-a")
+	[ -z "$2" ] && err
+
+	if append_dns "$2"
+	then
+		echo "Done!"
+	fi
+	;;
+
+"-h" | *)
+	help_msg
+	;;
+esac
+
+exit 0
+
+
diff --git a/.local/bin/moediary b/.local/bin/moediary
--- a/.local/bin/moediary
+++ b/.local/bin/moediary
@@ -7,11 +7,13 @@ readonly LINE=5
 readonly SEP="-----------"
 
 [ ! -d "$DIR" ] && mkdir "$DIR"
+
 cd "$DIR" || exit
 
-help()
+
+help_msg()
 {
-    cat << EOF
+	cat << EOF
 Moe Diary
 
 Usage: moediary [OPT]"
@@ -27,56 +29,59 @@ EOF
 
 case "$1" in
 "-t" | "--today")
-    DATE=$(date +"%d-%m-%Y")
-    
-    if [ ! -f "$DIR/${DATE}.txt" ]
-    then
-        printf "%s\n%s\n%s\n\n\n" "$SEP" "$DATE" "$SEP" > "$DIR/${DATE}.txt"
-    fi
-    
-    $EDITOR + "$DIR/${DATE}.txt"
-    ;;
-    
+	DATE=$(date +"%d-%m-%Y")
+	
+	if [ ! -f "$DIR/${DATE}.txt" ]
+	then
+		printf "%s\n%s\n%s\n\n\n" "$SEP" "$DATE" "$SEP" > "$DIR/${DATE}.txt"
+	fi
+	
+	$EDITOR + "$DIR/${DATE}.txt"
+	;;
+
 "-y" | "--yesterday" | "-o" | "--open" )
-    if [ "$1" = "-o" ] || [ "$1" = "--open" ]
-    then
-        [ -z "$2" ] && echo "Filename empty!" && exit 1
-        DATE="$2"
-    else
-        DATE="$(date --date="yesterday"  +"%d-%m-%Y").txt"
-    fi
-    
-    if [ -f "$DIR/${DATE}" ]
-    then
-        $EDITOR + "$DIR/${DATE}"
-    fi
-    
-    echo "Diary \"$DATE\" not found"
-    ;;
+	if [ "$1" = "-o" ] || [ "$1" = "--open" ]
+	then
+		[ -z "$2" ] && echo "Filename empty!" && exit 1
+		DATE="$2"
+	else
+		DATE="$(date --date="yesterday"  +"%d-%m-%Y").txt"
+	fi
+	
+	if [ -f "$DIR/${DATE}" ]
+	then
+		$EDITOR + "$DIR/${DATE}"
+	fi
+	
+	echo "Diary \"$DATE\" not found"
+	;;
 
 "-s" | "--show")
-    clear
-    for i in $(find "$DIR"/* | sort -r)
-    do
-        echo "[${i##*/}]"
-        if [ "$( file -b --mime-type "$i" | sed 's|/.*||')" != "text" ]
-        then
-            echo "-- cannot read this file --"
-        else
-            head -n "$LINE" "$i"
-        fi
-        echo;
-    done | less
-    ;;
+	clear
+	for i in $(find "$DIR"/* | sort -r)
+	do
+		echo "[${i##*/}]"
+		if [ "$( file -b --mime-type "$i" | sed 's|/.*||')" != "text" ]
+		then
+			echo "-- cannot read this file --"
+		else
+			head -n "$LINE" "$i"
+		fi
+		echo;
+	done | less
+	;;
 
-"-h" | "--help")
-    help
-    exit 0
-    ;;
+"" | "-h" | "--help")
+	help_msg
+	;;
 
 *)
-    printf "%s\n\n" "Invalid argument!"
-    help
-    exit 1
-    ;;
+	printf "%s\n\n" "Invalid argument!"
+	help_msg
+
+	exit 1
+	;;
 esac
+
+exit 0
+
diff --git a/.local/bin/moenotes b/.local/bin/moenotes
--- a/.local/bin/moenotes
+++ b/.local/bin/moenotes
@@ -7,9 +7,9 @@ readonly LINE=5
 [ ! -d "$DIR" ] && mkdir "$DIR"
 cd "$DIR" || exit
 
-help()
+help_msg()
 {
-    cat << EOF
+	cat << EOF
 Moe Notes
 
 Usage: moenotes [OPT]
@@ -24,47 +24,52 @@ EOF
 
 case "$1" in
 "-d" | "--delete")
-    [ -z "$2" ] && exit
-    
-    rm -i "$2"
-    ;;
+	[ -z "$2" ] && exit
+	
+	rm -i "$2"
+	;;
 
 "-o" | "--open")
-    if [ -z "$2" ];
-    then
-        cd "$DIR" || exit
-        $EDITOR
-        exit
-    fi
-    
-    $EDITOR + "$DIR/$2"
-    ;;
+	if [ -z "$2" ];
+	then
+		cd "$DIR" || exit
+		$EDITOR
+
+		exit 0
+	fi
+	
+	$EDITOR + "$DIR/$2"
+	;;
 
 "-s" | "--show")
 	clear
 	for i in $(find "$DIR"/* | sort -r);
 	do
-	    echo "--------"
-	    echo "[$i]"
-	    echo "--------"
-	    if [ "$( file -b --mime-type "$i" | sed 's|/.*||')" != "text" ];
-	    then
-	        echo "-- cannot read this file --"
-	    else
-	        head -n "$LINE" "$i"
-	    fi
-	    echo
+		echo "[$i]"
+
+		if [ "$( file -b --mime-type "$i" | sed 's|/.*||')" != "text" ];
+		then
+			printf "%s\n" "-- cannot read this file --"
+		else
+			head -n "$LINE" "$i"
+			echo
+		fi
+		printf "\n%s\n" "-------------"
+
 	done | less
 	;;
 
-"-h" | "--help")
-    help
-    exit 0
+"" | "-h" | "--help")
+	help_msg
 	;;
 
 *)
-    printf "%s\n\n" "Invalid argument!"
-    help
-    exit 1
+	printf "%s\n\n" "Invalid argument!"
+	help_msg
+
+	exit 1
 	;;
 esac
+
+exit 0
+
diff --git a/.local/bin/srv b/.local/bin/srv
--- a/.local/bin/srv
+++ b/.local/bin/srv
@@ -2,22 +2,26 @@
 
 __SU="doas" # or sudo
 
-help()
+#---------------------------------------------------#
+help_msg()
 {
-    cat << EOF
+	cat << EOF
 srv [OPT] [SERVICE]
     -s       - Start service
     -S       - Stop service
-    -r       - restart service
+    -r       - Restart service
+    -l       - Show all serices
     -add     - Add new serivce
     -del     - Delete service
     -stat    - Show status
     -show    - Show all services
+    -help    - Show help
 
 Examples:
      srv -s     SERVICE
      srv -S     SERVICE
      srv -r     SERVICE
+     srv -l
      srv -add   SERVICE
      srv -del   SERVICE
      srv -stat  SERVICE
@@ -26,58 +30,115 @@ Examples:
 EOF
 }
 
-chk_arg2()
+err()
 {
-    if [ -z "$2" ]
-    then
-        printf "%s\n\n" "Invalid argument!"
-        help
-        
-        exit 1
-    fi
+	printf "%s\n" "Invalid argument!" >&2
+	help_msg >&2
+
+	exit 1
 }
 
+start_srv()
+{
+	[ -z "$2" ] && err
 
+	$__SU rc-service "$2" start
+}
+
+stop_srv()
+{
+	[ -z "$2" ] && err
+
+	$__SU rc-service "$2" stop
+}
+
+restart_srv()
+{
+	[ -z "$2" ] && err
+
+	$__SU rc-service "$2" restart
+}
+
+list_srv()
+{
+	rc-service -l | column
+}
+
+add_srv()
+{
+	[ -z "$2" ] && err
+
+	$__SU rc-update add "$2"
+}
+
+del_srv()
+{
+	[ -z "$2" ] && err
+
+	$__SU rc-update delete "$2"
+}
+
+stat_srv()
+{
+	if [ -n "$2" ]
+	then
+		rc-service "$2" status
+	else
+		rc-status
+	fi
+}
+
+show_srv()
+{
+	rc-update show
+}
+
+#---------------------------------------------------#
 case "$1" in
 "-s")
-    chk_arg2 "$@"
-    $__SU rc-service "$2" start
-    ;;
+	start_srv "$@"
+	;;
 
 "-S")
-    chk_arg2 "$@"
-    $__SU rc-service "$2" stop
-    ;;
+	stop_srv "$@"
+        ;;
 
 "-r")
-    chk_arg2 "$@"
-    $__SU rc-service "$2" restart
-    ;;
+	restart_srv "$@"
+	;;
+
+"-l")
+	list_srv "$@"
+	;;
 
 "-add")
-    chk_arg2 "$@"
-    $__SU rc-update add "$2"
-    ;;
+	add_srv "$@"
+	;;
 
 "-del")
-    chk_arg2 "$@"
-    $__SU rc-update delete "$2"
-    ;;
+	del_srv "$@"
+	;;
 
 "-stat")
-    chk_arg2 "$@"
-    rc-service "$2" status
-    ;;
+	stat_srv "$@"
+	;;
 
 "-show")
-    rc-update show
-    ;;
+	show_srv "$@"
+	;;
 
-*)
-    help
-
-    exit 1
-    ;;
+"-help" | *)
+	help_msg
+	;;
 esac
+
+ret="$?"
+
+if [ "$ret" -ne "0" ]
+then
+	printf "%s\n" "Error occured" >&2
+
+	exit 1
+fi
 
 exit 0
