Update
Signed-off-by: Arthur Lapz <rlapz@gnuweeb.org>

diff --git a/.local/bin/srv b/.local/bin/srv
--- a/.local/bin/srv
+++ b/.local/bin/srv
@@ -6,46 +6,71 @@ help()
 {
     cat << EOF
 srv [OPT] [SERVICE]
+    -s       - Start service
+    -S       - Stop service
+    -r       - restart service
+    -add     - Add new serivce
+    -del     - Delete service
+    -stat    - Show status
+    -show    - Show all services
 
 Examples:
-     start   SERVICE
-     stop    SERVICE
-     restart SERVICE
-     add     SERVICE
-     delete  SERVICE
-     status  SERVICE
-     show
+     srv -s     SERVICE
+     srv -S     SERVICE
+     srv -r     SERVICE
+     srv -add   SERVICE
+     srv -del   SERVICE
+     srv -stat  SERVICE
+     srv -show
      
 EOF
 }
 
+chk_arg2()
+{
+    if [ -z "$2" ]
+    then
+        printf "%s\n\n" "Invalid argument!"
+        help
+        
+        exit 1
+    fi
+}
+
+
 case "$1" in
-"start")
+"-s")
+    chk_arg2 "$@"
     $__SU rc-service "$2" start
     ;;
 
-"stop")
+"-S")
+    chk_arg2 "$@"
     $__SU rc-service "$2" stop
     ;;
 
-"restart")
+"-r")
+    chk_arg2 "$@"
     $__SU rc-service "$2" restart
     ;;
 
-"add")
+"-add")
+    chk_arg2 "$@"
     $__SU rc-update add "$2"
     ;;
 
-"delete")
+"-del")
+    chk_arg2 "$@"
     $__SU rc-update delete "$2"
     ;;
 
-"show")
-    rc-update show
+"-stat")
+    chk_arg2 "$@"
+    rc-service "$2" status
     ;;
 
-"status")
-    rc-status "$2"
+"-show")
+    rc-update show
     ;;
 
 *)
@@ -54,3 +79,5 @@ case "$1" in
     exit 1
     ;;
 esac
+
+exit 0
